#
#
#
- name: install dnsmasq service
  apt:
    name: "dnsmasq"
    state: "present"

- name: set requested dnsmasq service state
  service:
    name: "dnsmasq"
    enabled: "{{ dnsmasq.enabled|default(yes) }}"

- name: set default dnsmasq settings
  template:
    src: "system.dnsmasq.default.j2"
    dest: "/etc/default/dnsmasq"
    owner: "root"
    group: "root"
    mode: 0644

- name: create config directory for dnsmasq
  file:
    path: "{{ dnsmasq.config_dir }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755

- name: update dnsmasq config
  template:
    src: "system.dnsmasq.conf.j2"
    dest: "{{ dnsmasq.config_dir }}/00_dnsmasq.conf"
    owner: "root"
    group: "root"
    mode: 0644

# zmask, is because this script should be
# last in alphabetic order
- name: set dhclient hook
  template:
    src: "system.dhclient.hook.j2"
    dest: "/etc/dhcp/dhclient-enter-hooks.d/zmasq"
    owner: "root"
    group: "root"
    mode: 0644

# disable /etc/resolv.conf rewrites
- name: restart dnsmasq and networking
  service:
    name: "{{ item }}"
    state: "restarted"
  with_items:
    - "dnsmasq"
    - "networking"

- name: update resolv.conf
  template:
    src: "system.resolv.conf.j2"
    dest: "/run/resolvconf/resolv.conf"
    owner: "root"
    group: "root"
    mode: 0644
