#
#
#
#
- name: generate mandatory locales
  command: locale-gen --purge en_US.UTF-8 ru_RU.UTF-8

- name: set default locale settings
  template:
    src: "system.locale.default.j2"
    dest: "/etc/default/locale"
    owner: "root"
    group: "root"
    mode: 0644

- name: locale - set localtime
  file:
    src: "/usr/share/zoneinfo/Europe/Moscow"
    dest: "/etc/localtime"
    owner: "root"
    group: "root"
    state: "link"
    force: yes

- name: locale - set timezone
  template:
    src: "system.timezone.j2"
    dest: "/etc/timezone"
    owner: "root"
    group: "root"
    mode: 0644
